// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0yPgrcc6Pm2nltUK-97mMA2hT_oNS5qU',
    appId: '1:1076436127342:web:087224bc3df7410757e07f',
    messagingSenderId: '1076436127342',
    projectId: 'prueba-8f504',
    authDomain: 'prueba-8f504.firebaseapp.com',
    storageBucket: 'prueba-8f504.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirxkG7YNnp4ZhErv8fOm2_sEk_paHzN8',
    appId: '1:1076436127342:android:e47192440351171857e07f',
    messagingSenderId: '1076436127342',
    projectId: 'prueba-8f504',
    storageBucket: 'prueba-8f504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsmzZHX_oOjML912Muq8N4_OyfeYgLQI',
    appId: '1:1076436127342:ios:8e73a01924dec81657e07f',
    messagingSenderId: '1076436127342',
    projectId: 'prueba-8f504',
    storageBucket: 'prueba-8f504.firebasestorage.app',
    iosBundleId: 'com.example.recu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxsmzZHX_oOjML912Muq8N4_OyfeYgLQI',
    appId: '1:1076436127342:ios:8e73a01924dec81657e07f',
    messagingSenderId: '1076436127342',
    projectId: 'prueba-8f504',
    storageBucket: 'prueba-8f504.firebasestorage.app',
    iosBundleId: 'com.example.recu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0yPgrcc6Pm2nltUK-97mMA2hT_oNS5qU',
    appId: '1:1076436127342:web:d62f6cca836aef3057e07f',
    messagingSenderId: '1076436127342',
    projectId: 'prueba-8f504',
    authDomain: 'prueba-8f504.firebaseapp.com',
    storageBucket: 'prueba-8f504.firebasestorage.app',
  );
}
